services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ../api
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/crud_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  streamlit:
    build:
      context: ../app
    environment:
      API_URL: http://api:8000/v1
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pgdata:
