version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
  - name: fct_order_items
    columns:
      - name: order_id
        tests: [not_null]
